#!/usr/bin/env bash
docker stop php-base-laminas
docker rm php-base-laminas

USE_TRAEFIK=false

DOMAIN=localdev.hc-sc.gc.ca
TRAEFIK_RULE='Host(`'$DOMAIN'`)'
TRAEFIK_TLS_MAIN_DOMAIN=$DOMAIN
TRAEFIK_TLS_SANS_DOMAIN=$DOMAIN

PORT=""
if [ ! $USE_TRAEFIK ]; then
    PORT="-p 80:80"
fi

docker run -d --name php-base-laminas \
    --net appnet \
    --restart unless-stopped \
    -v /etc/localtime:/etc/localtime:ro \
    -v /etc/timezone:/etc/timezone:ro \
    -e PHP_DEV_ENV=1 \
    $PORT \
    --label traefik.enable=$USE_TRAEFIK \
    --label traefik.http.routers.drupalwxt.rule=$TRAEFIK_RULE \
    --label traefik.http.routers.drupalwxt.entrypoints=websecure \
    --label traefik.http.routers.drupalwxt.tls=true \
    --label traefik.http.routers.drupalwxt.tls.domains[0].main=$TRAEFIK_TLS_MAIN_DOMAIN \
    --label traefik.http.routers.drupalwxt.tls.domains[0].sans=$TRAEFIK_TLS_SANS_DOMAIN \
    --label traefik.http.routers.drupalwxt_http.rule=$TRAEFIK_RULE \
    --label traefik.http.routers.drupalwxt_http.entrypoints=web \
    php-base-laminas:latest
