#!/usr/bin/env bash
docker stop php-base-laminas
docker rm php-base-laminas

docker run -d --name php-base-laminas \
    --net appnet \
    --restart unless-stopped \
    -v /etc/localtime:/etc/localtime:ro \
    -v /etc/timezone:/etc/timezone:ro \
    -e PHP_DEV_ENV=1 \
    --label traefik.enable=true \
    --label traefik.http.routers.lessons.rule='Host(`localdev.hc-sc.gc.ca`)' \
    --label traefik.http.routers.lessons_http.rule='Host(`localdev.hc-sc.gc.ca`)' \
    --label traefik.http.routers.lessons_http.entrypoints=web \
    -v /docker/php-base-laminas/code/module/ActiveDirectory:/var/www/module/ActiveDirectory \
    -v /docker/php-base-laminas/code/module/UserAuth:/var/www/module/UserAuth \
    php-base-laminas:latest
