<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
$this->metadata['title'] = $this->translate('Please check your mailbox to complete registration');
?>
<p>
<?=$this->translate('An email was sent you the email address you provided.
Please click on the link within that email to complete your registration.
The email was sent from <em>Authentication Service | Service d\'authentication <nobr>&lt;auth-service@notification.canada.ca&gt;</nobr></em>.
Please check your junk or spam folder if you did not receive it in five to ten minutes.
');?>
</p>
