<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
//$this->metadata['title'] = 'User Auth';
$this->metadata['extra-js'] = '/js/userauth-register.js';
?>

<div class="wb-frmvld">
    <form action="<?=$this->url('user/register',['locale'=>$this->lang]);?>" method="post" id="validation-example">
        <?if($this->errors && count($this->errors)):?>
            <section id="errors-validation-example" class="alert alert-danger" tabindex="-1">
                <h2><?=sprintf($this->translate("The form could not be submitted because %d error(s) was found."),count($this->errors));?></h2>
                <ul>
                    <?$nb=1;foreach($this->errors as $error):?>
                    <li><a href="#<?=$error['field'];?>">
                        <span class="prefix"><?=$this->translate('Error');?>&nbsp;<?=$nb++;?>: </span><?=$error['message'];?></a></li>
                    <?endforeach;?>
                </ul>
            </section>
        <?endif;?>
        <?if(count($this->passwordRules)):?>
        <details>
            <summary><?=$this->translate('Password rules');?></summary>
            <?if(isset($this->passwordRules['description'])):?>
                <p><?=$this->passwordRules['description'];?></p>
            <?else:?>
                <dl>
                    <?if(isset($this->passwordRules['minSize'])):?>
                        <dt><?=$this->translate('Minimum size of the password/passphrase');?></dt>
                        <dd><?=$this->passwordRules['minSize'];?></dd>
                    <?endif;?>

                    <?if(isset($this->passwordRules['minSize']) && count($this->passwordRules) > 1):?>
                        <dt><?=$this->translate('Your password must contain at least');?></dt>
                    <?endif;?>

                    <?if(isset($this->passwordRules['atLeastOneLowerCase'])):?>
                        <dd><?=$this->translate('one lower case letter');?></dd>
                    <?endif;?>
                    <?if(isset($this->passwordRules['atLeastOneUpperCase'])):?>
                        <dd><?=$this->translate('one upper case letter');?></dd>
                    <?endif;?>
                    <?if(isset($this->passwordRules['atLeastOneNumber'])):?>
                        <dd><?=$this->translate('one number');?></dd>
                    <?endif;?>
                    <?if(isset($this->passwordRules['atLeastOneSpecialCharacters'])):?>
                        <dd><?=sprintf($this->translate('one special character from this list: %s'), implode(' ',str_split($this->passwordRules['atLeastOneSpecialCharacters'])));?></dd>
                    <?endif;?>
                    <?if(isset($this->passwordRules['additionalRules'])):?>
                        <dd><?=$this->translate($this->passwordRules['additionalRules']);?></dd>
                    <?endif;?>
                </dl>
            <?endif;?>
        </details>
        <?endif;?>

        <div class="form-group">
            <label for="email" class="required"><span class="field-name"><?=$this->translate('Email', 'layout');?></span> <strong class="required">(<?=$this->translate('required', 'layout');?>)</strong></label>
            <input class="form-control" id="email" name="email" type="text" autocomplete="email" required="required" value="<?=$this->email??'';?>" />
        </div>

        <div class="form-group">
            <label for="password" class="required"><span class="field-name"><?=$this->translate('Password', 'layout');?></span> <strong class="required">(<?=$this->translate('required', 'layout');?>)</strong></label>
            <input class="form-control" id="password" name="password" type="password" autocomplete="off" required="required" />
        </div>
        <div class="form-group">
            <label for="confirmPassword" class="required"><span class="field-name"><?=$this->translate('Confirm password', 'layout');?></span> <strong class="required">(<?=$this->translate('required', 'layout');?>)</strong></label>
            <input class="form-control" id="confirmPassword" name="confirmPassword" type="password" autocomplete="off" required="required" />
        </div>
        <button type="submit" class="btn btn-primary"><?=$this->translate('Register', 'layout');?></button>
    </form>
</div>
<script>
var passwordRules = <?=json_encode($this->passwordRules);?>;
var passwordRulesTranslation = {
    "minSize":"<?=sprintf($this->translate('Your password must contain at least %d characters.'), $this->passwordRules['minSize']);?>",
    "atLeastOneLowerCase":"<?=$this->translate('Your password must contain at least one lower case character.');?>",
    "atLeastOneUpperCase":"<?=$this->translate('Your password must contain at least one upper case character.');?>",
    "atLeastOneNumber":"<?=$this->translate('Your password must contain at least one number.');?>",
    "atLeastOneSpecialCharacters":"<?=$this->translate('Your password must contain at least one special character.');?>",
    "confirmDoesNotMatch":"<?=$this->translate('Your password and confirmation must match.');?>"
}
</script>
