<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
$this->metadata['title'] = $this->translate('Reset password');
?>
<p><?=$this->translate('If you lost your password, you can reset your password using the form below.');?></p>

<?if($this->postedData):?>
    <div class="alert alert-<?if($this->success):?>success<?else:?>danger<?endif;?>">
        <p><?=$this->message;?></p>
    </div>
<?endif;?>

<div class="wb-frmvld">
    <form action="?" method="post" id="reset-password">
        <div class="form-group">
            <label for="email" class="required"><?=$this->translate('Enter your <span class="field-name">email address</span>');?> <strong class="required">(<?=$this->translate('required');?>)</strong></label>
            <input class="form-control" id="email" name="email" type="text" autocomplete="email" required="required" />
        </div>
        <input type="submit" value="<?=$this->translate('Submit');?>" class="btn btn-primary">
    </form>
</div>

